name: 'Send review reminder'
description: 'Reminds about pending GitHub pull request review on twist.com'
author: 'Piotr Wilczek'
inputs:
  review_time_ms:
    description: 'Required review time'
    required: true
    default: '86400000'
  ignore_authors:
    description: 'Ignore pull requests from those authors'
    required: false
  twist_url:
    description: 'Twist integration url to post reminder messages'
    required: true
  message:
    description: 'Reminder message'
    required: true
    default: '%reviewer%, please review [#%pr_number% - %pr_title%](%pr_url%)'
  token:
    description: 'GitHub token'
    required: true
  ignore_draft_prs:
    description: 'Whether we should ignore draft PRs when checking for pending reviews'
    required: true
    default: false
  ignore_labels:
    description: 'If provided any PRs with these labels will skip the review reminder check'
    required: false
  ignore_prs_with_failing_checks:
    description: 'If the PR has any failing or errored status checks, ignore it'
    required: true
    default: false
  author_to_twist_mapping:
    description: 'A mapping of each possible reviewers GitHub username to their associated Twist user id. If provided it will ensure the correct user is notified in Twist when a review is overdue'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
